spring:
    application:
        name: 12_SpringBoot_Actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: 'beans'
  endpoint:
    shutdown:
      enabled: true